# Database Configuration
adapters.postgres.host=${DB_HOST}
adapters.postgres.port=5432
adapters.postgres.database=${DATABASE_AUTH}
adapters.postgres.username=${USERNAME_AUTH}
adapters.postgres.password=${PASSWORD_AUTH}

# JWT Configuration
jwt.secret=${JWT_SECRET_AUTH}

# Server
server.port=8080