server:
  port: 8080
spring:
  application:
    name: "Authentication"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  postgres:
    database: ${DATABASE_AUTH}
    host: "localhost"
    port: 5432
    username: ${USERNAME_AUTH}
    password: ${PASSWORD_AUTH}
    schema: "public"
    pool:
      initial-size: 12
      max-size: 15
      max-idle-time: 10

  reactive-web:
    base-path: "api/v1"

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}